# -*- coding: utf-8 -*-
"""Code_Alpha_Task1_Credit_Scoring_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRu2QiCMXqnijJS4d50-n6rUStKeUCBu

# **Credit Scoring Model**

### **CodeAlpha Machine Learning Internship - Task 1**

**Intern Name:** Radhika

**Platform:** Google Colab

**Programming Language:** Machine Learning



## 📌 Project Objective

The objective of this project is to develop a machine learning model that can predict whether a customer represents a good or bad credit risk based on financial and personal information. Credit scoring helps financial institutions make informed lending decisions and reduce the risk of loan defaults.

## Import Required Libraries

This section imports all the necessary libraries required for data analysis, visualization, machine learning model development, and model evaluation.
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

"""## Step 1: Upload and Load Dataset
The German Credit Dataset is loaded into the notebook for analysis and machine learning model development. This dataset contains customer financial and personal information that will be used to predict credit risk.
"""

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("german_credit_data.csv")

"""## Step 2: Exploratory Data Analysis (EDA)

The dataset structure, missing values, and summary statistics are examined.
"""

df.head()

"""## Step 3: Dataset Overview

Before building the machine learning model, it is important to understand the size, structure, and characteristics of the dataset.
"""

print("Dataset Shape:", df.shape)

df.info()

df.describe()

"""## Step 4: Missing Values Analysis

This step identifies missing values present in the dataset. Handling missing data is an important part of data preprocessing.
"""

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title("Missing Values Heatmap")
plt.show()

"""## Step 5: Data Cleaning

### Missing Values Analysis
The heatmap shows that missing values are present in the **Saving Accounts** and **Checking Account** columns, while all other features contain complete records.
"""

df['Saving accounts'] = df['Saving accounts'].fillna('Unknown')
df['Checking account'] = df['Checking account'].fillna('Unknown')

df.isnull().sum()

"""## Step 6: Exploratory Data Analysis

Exploratory Data Analysis helps identify trends, distributions, and relationships among variables within the dataset.
"""

df.head()

"""### Gender Distribution
The dataset contains more male applicants than female applicants, indicating a gender imbalance in the applicant population.
"""

plt.figure(figsize=(8,5))
sns.countplot(x='Sex', data=df)
plt.title("Gender Distribution")
plt.show()

"""### Age Distribution
Most applicants belong to the **20–40 years** age group, with fewer applicants in older age categories.
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.show()

"""### Age Distribution by Gender
The age distribution is similar across genders, although male applicants show a slightly higher median age.
"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Sex', y='Age', data=df)
plt.title("Age Distribution by Gender")
plt.show()

"""### Step-7: Housing Distribution
This visualization shows the distribution of applicants based on their housing status (own, rent, or free).
"""

plt.figure(figsize=(8,5))
sns.countplot(x='Housing', data=df)
plt.title("Housing Distribution")
plt.show()

"""### Step-8: Saving Accounts Distribution
This chart shows the distribution of applicants according to their saving account status.
"""

plt.figure(figsize=(8,5))
sns.countplot(x='Saving accounts', data=df)
plt.title("Saving Accounts Distribution")
plt.show()

"""### Step-9: Checking Account Distribution
This visualization represents the checking account status of loan applicants.
"""

plt.figure(figsize=(8,5))
sns.countplot(x='Checking account', data=df)
plt.title("Checking Account Distribution")
plt.show()

"""### Step-10: Loan Purpose Distribution
The chart illustrates the different purposes for which applicants requested credit.
"""

plt.figure(figsize=(10,6))
sns.countplot(y='Purpose', data=df)
plt.title("Loan Purpose Distribution")
plt.show()

"""### Step-11: Credit Amount Distribution
This histogram displays the distribution of credit amounts requested by applicants.
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Credit amount'], bins=30, kde=True)
plt.title("Credit Amount Distribution")
plt.show()

"""### Step-12: Loan Duration Distribution
This chart shows the distribution of loan durations among applicants.
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Duration'], bins=20, kde=True)
plt.title("Loan Duration Distribution")
plt.show()

"""### Step-13: Feature Encoding
Categorical variables are converted into numerical form using Label Encoding to prepare the dataset for machine learning algorithms.
"""

from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

le = LabelEncoder()

for col in df_encoded.select_dtypes(include='object').columns:
    df_encoded[col] = le.fit_transform(df_encoded[col])

df_encoded.head()

"""### Step-14: Correlation Analysis
The correlation heatmap helps identify relationships between variables and highlights features that may influence credit risk.
"""

plt.figure(figsize=(10,8))
sns.heatmap(df_encoded.corr(),
            annot=True,
            cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

print(df.columns.tolist())

df.head()
df.shape
df.tail()

print(df.columns)

df.shape

df.head()

"""### Step 15: Risk Column Create"""

df['Risk'] = ((df['Credit amount'] > 5000) & (df['Duration'] > 24)).astype(int)

df['Risk'].value_counts()

"""### Step 16: Encoding Again with Risk"""

from sklearn.preprocessing import LabelEncoder

df_model = df.copy()

le = LabelEncoder()

for col in df_model.select_dtypes(include='object').columns:
    df_model[col] = le.fit_transform(df_model[col])

df_model.head()

"""### Step 17: Features & Target"""

X = df_model.drop('Risk', axis=1)
y = df_model['Risk']

"""### Step 18: Train-Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""### Step 19: Random Forest Model"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

"""### Step 20: Prediction"""

y_pred = model.predict(X_test)

"""### Step 21: Accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""### Step 22: Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""### Step 23: Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""### Step 24: Feature Importance"""

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

"""### Step 25: Feature Importance Graph"""

plt.figure(figsize=(8,5))

sns.barplot(
    x='Importance',
    y='Feature',
    data=importance
)

plt.title('Feature Importance')
plt.show()

"""### Project Insights

1. Credit Amount and Duration showed the highest impact on credit risk.
2. Customers with higher loan amounts and longer repayment durations were more likely to be classified as high risk.
3. Random Forest performed effectively in identifying risky applicants.
4. Feature importance analysis helped identify key factors influencing credit decisions.
5. The model can assist financial institutions in preliminary credit risk assessment.

### **Conclusion**

A Credit Scoring Model was developed using machine learning techniques to assess applicant risk. Data preprocessing, exploratory data analysis, feature encoding, correlation analysis, and Random Forest classification were performed. The model successfully classified applicants into risk categories and identified the most influential factors affecting creditworthiness. This approach can support faster and more consistent loan approval decisions.
"""