# -*- coding: utf-8 -*-
"""CodeAlpha_Task2_Emotion_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-sU-FQdmRgj9t6r8szneynU4PGu4O8B

# **Emotion Recognition from Speech**

### **CodeAlpha Machine Learning Internship - Task 2**

**Intern Name:** Radhika

**Platform:** Google Colab

**Programming Language:** Machine Learning

## Dataset Preparation

In this step, the RAVDESS (Ryerson Audio-Visual Database of Emotional Speech and Song) dataset is loaded and organized.

The dataset contains speech recordings representing different emotions such as:

- Neutral
- Calm
- Happy
- Sad
- Angry
- Fearful
- Disgust
- Surprised

Audio files are collected from all actor folders and corresponding emotion labels are extracted from the filenames for further processing.

## Mount Google Drive

The Google Drive is mounted to access the RAVDESS dataset stored in the user's drive. This allows the notebook to read audio files directly from Google Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Install & Import Required Libraries

Required libraries are installed and imported for audio processing, data handling, visualization, machine learning, and deep learning model development.

Libraries Used:
- Librosa (Audio Feature Extraction)
- NumPy (Numerical Computation)
- Pandas (Data Handling)
- Matplotlib & Seaborn (Visualization)
- Scikit-learn (Preprocessing and Data Splitting)
- TensorFlow/Keras (Deep Learning Model)
"""

!pip install librosa soundfile tensorflow -q

import os
import librosa
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D
from tensorflow.keras.layers import Flatten, Dropout
from tensorflow.keras.utils import to_categorical

"""## Verify Dataset Location

The dataset path is checked to ensure that the RAVDESS dataset is correctly loaded from Google Drive before further processing.
"""

dataset_path = "/content/drive/MyDrive/RAVDESS"

print(os.listdir(dataset_path)[:5])

"""## Explore Dataset Structure

The RAVDESS dataset is organized into multiple actor folders. This step verifies the folder structure and counts the total number of actors available in the dataset.
"""

print(os.listdir("/content/drive/MyDrive/RAVDESS/archive (1)")[:5])

actors = os.listdir("/content/drive/MyDrive/RAVDESS/archive (1)")
print("Total Actors:", len(actors))

"""## Extract Emotion Labels

Each audio filename in the RAVDESS dataset contains an emotion code. These codes are mapped to their corresponding emotion labels such as Happy, Sad, Angry, Fearful, Calm, Neutral, Disgust, and Surprised.

Audio file paths and emotion labels are collected for model training.
"""

emotion_map = {
    "01": "neutral",
    "02": "calm",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "fearful",
    "07": "disgust",
    "08": "surprised"
}

data = []
labels = []

dataset_path = "/content/drive/MyDrive/RAVDESS/archive (1)"

for actor in os.listdir(dataset_path):
    actor_path = os.path.join(dataset_path, actor)

    if os.path.isdir(actor_path):
        for file in os.listdir(actor_path):

            if file.endswith(".wav"):

                emotion_code = file.split("-")[2]

                if emotion_code in emotion_map:

                    file_path = os.path.join(actor_path, file)

                    data.append(file_path)
                    labels.append(emotion_map[emotion_code])

print("Total Audio Files:", len(data))
print("Sample Labels:", labels[:10])

"""## Feature Extraction using MFCC

Mel-Frequency Cepstral Coefficients (MFCCs) are extracted from each audio file. MFCC features capture important characteristics of speech signals and are widely used in speech emotion recognition tasks.

For each audio sample:
- Audio is loaded
- MFCC features are extracted
- Mean values are computed to create a fixed-length feature vector
"""

def extract_features(file_path):
    audio, sample_rate = librosa.load(file_path, duration=3, offset=0.5)

    mfcc = librosa.feature.mfcc(
        y=audio,
        sr=sample_rate,
        n_mfcc=40
    )

    return np.mean(mfcc.T, axis=0)

"""## Generate Feature Dataset
The feature extraction function is applied to all audio files in the dataset. The resulting MFCC feature vectors are stored along with their corresponding emotion labels to create the final dataset for model training.
"""

X = []
y = []

for file_path, label in zip(data, labels):
    try:
        feature = extract_features(file_path)

        X.append(feature)
        y.append(label)

    except:
        pass

print("Features Extracted:", len(X))

"""## Label Encoding

Machine learning models work with numerical values rather than text labels. Therefore, emotion labels are converted into numerical form using Label Encoding.

The encoded labels are then transformed into categorical format using One-Hot Encoding, making them suitable for multi-class classification.
"""

X = np.array(X)
y = np.array(y)

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

y_categorical = to_categorical(y_encoded)

"""## Train-Test Split

The dataset is divided into training and testing sets.

- Training Set: Used to train the model.
- Testing Set: Used to evaluate model performance on unseen data.

This helps assess the model's ability to generalize to new speech samples.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_categorical,
    test_size=0.2,
    random_state=42
)

"""## Build CNN Model

A Convolutional Neural Network (CNN) is created to learn patterns from MFCC audio features.

The model consists of:
- Convolution Layers for feature learning
- Max Pooling Layers for dimensionality reduction
- Dropout Layers to prevent overfitting
- Dense Layers for classification

The final output layer predicts the emotion category of the speech sample.
"""

model = Sequential()
...

model = Sequential()

model.add(Conv1D(64, 3, activation='relu',
                 input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(2))

model.add(Conv1D(128, 3, activation='relu'))
model.add(MaxPooling1D(2))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(y_categorical.shape[1],
                activation='softmax'))

model.summary()

print(X_train.shape)
print(y_train.shape)

"""## Model Compilation

The CNN model is compiled using:

- Adam Optimizer for efficient learning
- Categorical Crossentropy Loss for multi-class classification
- Accuracy as the evaluation metric

This prepares the model for training.
"""

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""## Model Training

The CNN model is trained using the extracted MFCC features and encoded emotion labels.

During training:
- The model learns emotional speech patterns.
- Validation data is used to monitor performance.
- Accuracy and loss values are recorded for analysis.
"""

history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test, y_test)
)

"""## Model Evaluation

The trained model is evaluated on the testing dataset.

Evaluation metrics such as accuracy are used to measure how effectively the model can recognize emotions from unseen speech samples.
"""

loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

"""## Training Performance Visualization

Training and validation accuracy/loss graphs are plotted to analyze the learning behavior of the model.

These visualizations help identify:
- Model convergence
- Overfitting
- Underfitting
- Overall training performance
"""

plt.plot(history.history['accuracy'])

"""## Training Accuracy Graph

The graph below shows how the model's training accuracy changes across epochs.
A continuously increasing curve indicates that the CNN model is learning emotional speech patterns from the extracted MFCC features.
"""

plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'])
plt.title('Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()

"""## Validation Accuracy Graph

Validation accuracy is used to measure how well the model performs on unseen data.
This helps determine whether the model generalizes well beyond the training dataset.
"""

plt.figure(figsize=(8,5))
plt.plot(history.history['val_accuracy'])
plt.title('Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()

"""## Training Loss Graph

Training loss represents the error made by the model during training.
A decreasing loss value indicates that the model is improving its predictions over time.
"""

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'])
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.show()

"""## Validation Loss Graph

Validation loss is calculated using unseen test samples.
Monitoring validation loss helps identify overfitting and evaluate model performance on real-world data.
"""

plt.figure(figsize=(8,5))
plt.plot(history.history['val_loss'])
plt.title('Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.show()

"""## Model Saving

After training and evaluation, the trained CNN model is saved in Keras format (.keras). This allows the model to be reused later without retraining and avoids legacy HDF5 warnings.
"""

model.save('emotion_recognition_model.keras')

print("Model Saved Successfully")

"""## Project Conclusion

A Speech Emotion Recognition System was successfully developed using
MFCC feature extraction and a Convolutional Neural Network (CNN).

The model was trained and evaluated on emotional speech data and achieved
approximately 49% test accuracy.

This project demonstrates the application of Deep Learning techniques
for automatic emotion recognition from audio signals.
"""